import './setup_mock_auth';
import { preloadAllSchedulesSync } from '../utils/scheduleNodeLoader';
preloadAllSchedulesSync();

console.log("Running all test suites sequentially...");
await import('./test_ondemand_schedules');
await import('./test_dates');
await import('./test_attendance');
await import('./test_schedule_sync');
await import('./test_homework');
await import('./test_telegram_webapp');
await import('./test_samgtu_parser');
await import('./test_faid_schedule');
await import('./test_faid_attendance');
await import('./verify_student_ux');
await import('./test_ingt209_schedule');
await import('./test_qa_ingt209_verification');
await import('./test_bugreport_feature');
await import('./test_logger_diagnostics');
await import('./test_telemetry');
await import('./test_cancellation_and_privacy');
await import('./test_security_audit');
await import('./test_auth_hashes');
await import('./test_initdata_auth');
await import('./test_api_v3');
await import('./test_attendance_storage');
await import('./test_group_dedup_and_ingt3');
await import('./test_roster_cloud_sync');
await import('./test_roster_provider');
await import('./test_attendance_word_export_verification');
await import('./test_tma_resilience_e2e');
await import('./test_sunday_week_rollover_regression');
await import('./test_semester_preload');
await import('./test_audit_deep');
await import('./test_sanitization');
await import('./test_schedule_url');
await import('./test_kv_backup');
await import('./test_privacy_p0');
await import('./test_bell_schedule');
await import('./test_attendance_merge');
await import('./test_tma_word_export');
const { runHomeworkLifecycleStressTest } = await import('./test_homework_lifecycle_stress');
await runHomeworkLifecycleStressTest();
console.log("\n=================================================");
console.log("       ALL TEST SUITES COMPLETED SUCCESSFULLY  ");
console.log("=================================================");
